In [ ]:
import numpy as np
y=[1,1,0,1]
px1=[0.8,0.4,0.2,0.9]


In [ ]:
def likelihood(X,Y):
    lh=1
    for i in range (len(Y)):
        lh*=(X[i]**Y[i])*((1-X[i])**(1-Y[i]))
    print(lh)

In [ ]:
print(likelihood(px1,y))

0.23040000000000005
None


In [ ]:
y1=[1,1,0,1]
px2=[0.8,0.4,0.2,0.9]
def loglikelihood(X,Y):
    lh=1
    for i in range(len(Y)):
        loglikelihood=np.sum(Y[i]*np.log(X[i])+(1-Y[i])*np.log(1-X[i]))
    print(lh)

In [ ]:
print(loglikelihood(px2,y1))

1
None


In [ ]:
import math
Y=[1,1,0,0]
X=np.array([[1,0.4,-0.2],[1,0.6,-0.5],[1,-0.3,0.8],[1,-0.7,0.5]])
theta=np.array([[0.5,1,2],[-0.5,1,2],[0.5,1,-2],[-0.5,-1,-2]])
PX=1/(1+np.exp(-np.dot(X,theta.T)))
px=PX.T
_px=1-px
print(px)
pxY=pow(px,Y)
print(pxY)
pxy=pow(px,y)
L=np.prod(pxy,axis=1)*np.prod(pxy,axis=1)
print(L)
print(theta[np.argmax(L),:])
# z=[]
# for i in range(len(y)):
#     z=t0[i]*x0[i]+t1[i]*x1[i]+t2[i]*x2[i]
#     print("z:",z)
#     px=1/(1+math.exp(-z))
#     print("px:",px)




[[0.62245933 0.52497919 0.85814894 0.68997448]
 [0.37754067 0.2890505  0.68997448 0.450166  ]
 [0.78583498 0.89090318 0.19781611 0.23147522]
 [0.37754067 0.47502081 0.14185106 0.31002552]]
[[0.62245933 0.52497919 1.         1.        ]
 [0.37754067 0.2890505  1.         1.        ]
 [0.78583498 0.89090318 1.         1.        ]
 [0.37754067 0.47502081 1.         1.        ]]
[0.10678399 0.01190899 0.49014405 0.03216272]
[ 0.5  1.  -2. ]
